<a href="https://colab.research.google.com/github/jhamidi1/Data201-Spring/blob/main/data201_class1_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Class 1 – Python Foundations (Student Notebook)

Bridge goal: translate familiar R patterns into Python.

Class 1 (Student Version): Python Fundamentals for R Users
Course: Intro to Data Analysis in Python
Background assumed: R, linear/logistic regression, basic ggplot2


=====================================================
 HOW TO USE THIS NOTEBOOK
=====================================================
 - Run cells top to bottom
 - Read the comments carefully
 - Complete all TODO sections
 - Predict outputs BEFORE running when prompted

=====================================================
 0. Setup
 =====================================================

In [22]:
import numpy as np
import pandas as pd

 =====================================================
 1. First Contact: Python vs R
 =====================================================

 In R:
 x <- c(1, 2, 3)
 mean(x)

 In Python, we must say WHICH library computes the mean.

In [23]:
x = [1, 2, 3]

**Exercise**
1. Try np.mean(x)
2. What happens if you try mean(x)?

In [26]:
np.mean(x)

np.float64(2.0)

In [25]:
mean(x)

NameError: name 'mean' is not defined

When I try mean(x), Python gives a NameError because the function mean is not defined. In Python, we must import a library like NumPy before using the mean function.


# 2. Objects, Types, and Explicitness

In [27]:
x_int = 3
x_float = 3.0
x_bool = True
x_none = None

**Exercise:**
Use type() to check the type of each object above.

In [28]:
type(x_int)
type(x_float)
type(x_bool)
type(x_none)

NoneType

 **Question:**
Which of these behaves most like NA in R? Which does NOT? None is most like NA in R because it means there is no value. The others (3, 3.0, and True) are real values, so they are not like NA.

# 3. Core Data Structures

**A. Lists** (similar to flexible R lists)

In [29]:
L = [1, 2, 3, 4]

**Exercise**
1. Access the first element of L
2. Access the last element of L


Predict before running:
What will L[1:3] return?

In [30]:
L[0]

1

In [31]:
L[-1]

4

In [32]:
L[1:3]

[2, 3]

**B. Tuples** (immutable lists) ---

In [33]:
T = (1, 2, 3)

**Question:**

---


Why might immutability be useful? Immutability is useful because the data cant accidentally be changed. This makes programs safer and easier to debug.

**C. Dictionaries** (named structures)


In [34]:
D = {"a": 10, "b": 20, "c": 30}

**Exercise**


In [35]:
D["b"]

20

# 4. Control Flow


In [36]:
x = 5

**A. If/elif/else statements**

**Exercise**
Write an if/elif/else statement that sets:


sign = "positive", "negative", or "zero"

In [37]:
if x > 0:
    sign = "positive"
elif x < 0:
    sign = "negative"
else:
    sign = "zero"

**B. For loops**

**Exercise**
Use a for-loop to create a list of squares from 0 to 4

** C. List comprehension** (Pythonic shortcut)

**Exercise**
Rewrite the previous loop using a list comprehension

In [38]:
#List comprehension

# 5. NumPy: Vectorized Computation

In [39]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

Predict BEFORE running:
What do you expect x + y to return?


**Exercise**

In [40]:
x + y

array([11, 22, 33, 44])

In [42]:
x * y

array([ 10,  40,  90, 160])

In [43]:
x + 5

array([6, 7, 8, 9])

In [44]:
np.mean(x)
np.std(x)

np.float64(1.118033988749895)

 Conditional logic (like ifelse in R)

**Exercise**

In [45]:
np.where(x > 2, x, 0)

array([0, 0, 3, 4])

# 6. Common Pitfalls for R Users


In [47]:
L = [1, 2, 3]

Predict:  
What will happen if you try L + 1?


**Exercise**

Try it and explain the result

---



In [48]:
L + 1

TypeError: can only concatenate list (not "int") to list

# 7. Active Learning Exercise (15–20 minutes)

 R code:
` x <- c(2, 4, 6, 8)`

` y <- ifelse(x > 4, x / 2, x * 2)`

 `mean(y)`


**TASK:**
1. Translate the code above into Python
2. Predict the value of y BEFORE computing
3. Compute mean(y)


In [49]:
x = np.array([2, 4, 6, 8])

In [50]:
y = np.where(x > 4, x / 2, x * 2)

In [51]:
np.mean(y)

np.float64(4.75)

# 8. Wrap-Up Reflection

In 2–3 sentences:
 - What felt most different from R?
 - What felt familiar?
 - What questions do you still have?

 What felt most different from R was that Python requires importing libraries like NumPy to do things that are built in in R, lile calculating the mean. What felt familiar was working with arrays and conditional logic, since they act similar to vectors and ifelse in R. I do not have much questions but I am excited to learn more about Python and its similarties and differences to R.